# left-side user profile
avatar: # by default https://octodex.github.com/images/baracktocat.jpg
location:  Bei Jing, China
email: 675495787[at]qq.com
social:
  github: https://github.com/xxxspy
  weibo: https://weibo.com/1312359657
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gsc: # google custom search code
