# left-side user profile
favicon: /images/head_3.png
avatar: /images/head.png
location:  Bei Jing, China
email: eprime[at]163.com
social:
  github: https://github.com/xxxspy
  weibo: https://weibo.com/1312359657
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gsc: # google custom search code
